### ISSUE TITLE
Error while implementing PP 

### ISSUE THREAD

**Issue by surajnagaje** [yeliqseu/sparsenc#2]
I have created all the binary files. I am trying to run the PP by using **./sncDecoders WINDWRAP PP 10 3 1 0 0 1 2 1**  through command window. While running it is giving an error like **WARNING: PP decoder only applies to perpetual codes.** 
I have used WINDWRAP as code type still it is giving this error.
Please guide how to run PP.

**Comment by yeliqseu** [comment]
Try:

`./sncDecoders WINDWRAP PP 10000 1000 0 1 4 1 8 0`

This encodes across 10 packets (10000/1000=10), where size_b=1 corresponds to a smooth version of perpetual codes, the band width is 4. Your parameters are apparently wrong since size_b, size_g are all zeros. For perpetual codes, size_c should be 0, which means no precoding needs to be applied. Perpetual code should not be systematic (at least it is not designed as so). 

I would suggest you to read the perpetual code paper more carefully to understand the principles of the parameters.
